In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [7]:

student = pd.read_csv("student_performance_own_dataset.csv")

student.head()

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1001,Aarav Kumar,Male,80.0,12.0,80.0,0.0,Medium,46.0,2.4,80.0,True
1,1002,Aditya Reddy,Female,80.0,12.0,85.0,3.0,Low,51.0,2.6,80.0,False
2,1003,Ananya Rao,Male,70.0,12.0,92.0,2.0,Medium,53.0,3.7,70.0,False
3,1004,Arjun Gupta,Male,85.0,15.0,75.0,0.0,Medium,53.0,2.9,85.0,False
4,1005,Diya Pillai,Male,NaN,25.0,55.0,3.0,Medium,53.0,6.6,98.0,False

In [8]:
print("Dataset Shape:", student.shape)
print("No of Rows", student.shape[0])
print("No of Columnss", student.shape[1])

Dataset Shape: (150, 12)
No of Rows 150
No of Columnss 12

In [9]:
print("\nColumn Names:")
print(student.columns)

print("\nDataset Information:")
print(student.info())

Column Names:
Index(['StudentID', 'Name', 'Gender', 'AttendanceRate', 'StudyHoursPerWeek',
       'PreviousGrade', 'ExtracurricularActivities', 'ParentalSupport',
       'FinalGrade', 'Study Hours', 'Attendance (%)', 'Online Classes Taken'],
      dtype='object')

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  150 non-null    int64
 1   Name                       150 non-null    object
 2   Gender                     149 non-null    object
 3   AttendanceRate             149 non-null    float64
 4   StudyHoursPerWeek          149 non-null    float64
 5   PreviousGrade              149 non-null    float64
 6   ExtracurricularActivities  149 non-null    float64
 7   ParentalSupport            149 non-null    object
 8   FinalGrade                 149 non-null    float64
 9   Study Hours                150 non-null    float64
 10  Attendance (%)             150 non-null    float64
 11  Online Classes Taken       150 non-null    bool
dtypes: bool(1), float64(7), int64(1), object(3)
memory usage: 13.2+ KB
None

In [10]:
print("\nStatistical Summary:")
student.describe().transpose()

Statistical Summary:

,count,mean,std,min,25%,50%,75%,max
StudentID,150.0,1075.500000,43.445368,1001.0,1038.25,1075.50,1112.75,1150.0
AttendanceRate,149.0,84.926174,8.782733,70.0,80.00,85.00,92.00,98.0
StudyHoursPerWeek,149.0,18.107383,7.219662,8.0,12.00,18.00,25.00,30.0
PreviousGrade,149.0,75.684564,12.071906,55.0,65.00,78.00,88.00,92.0
ExtracurricularActivities,149.0,1.395973,1.143837,0.0,0.00,1.00,2.00,3.0
FinalGrade,149.0,50.530201,6.467755,40.0,46.00,50.00,56.00,65.0
Study Hours,150.0,4.431333,1.929187,-2.5,2.80,4.35,6.00,8.7
Attendance (%),150.0,85.546667,10.212893,70.0,80.00,86.50,92.00,150.0

In [11]:
student.columns = (
    student.columns
    .str.strip()
    .str.replace(' ', '_')
    .str.replace(r'[%()]', '', regex=True)
)

print(student.columns)

Index(['StudentID', 'Name', 'Gender', 'AttendanceRate', 'StudyHoursPerWeek',
       'PreviousGrade', 'ExtracurricularActivities', 'ParentalSupport',
       'FinalGrade', 'Study_Hours', 'Attendance_', 'Online_Classes_Taken'],
      dtype='object')

In [12]:
student.loc[student['Study_Hours'] < 0, 'Study_Hours'] = np.nan
student.loc[student['Attendance_'] > 100, 'Attendance_'] = np.nan

In [13]:
print(student.isnull().sum())

StudentID                    0
Name                         0
Gender                       1
AttendanceRate               1
StudyHoursPerWeek            1
PreviousGrade                1
ExtracurricularActivities    1
ParentalSupport              1
FinalGrade                   1
Study_Hours                  1
Attendance_                  1
Online_Classes_Taken         0
dtype: int64

In [14]:
student = student.drop(columns=['StudentID', 'Name'])

print(student.columns)

Index(['Gender', 'AttendanceRate', 'StudyHoursPerWeek', 'PreviousGrade',
       'ExtracurricularActivities', 'ParentalSupport', 'FinalGrade',
       'Study_Hours', 'Attendance_', 'Online_Classes_Taken'],
      dtype='object')

In [15]:
num_cols = student.select_dtypes(include='number').columns

print("Before numerical columns")
print("*" * 30)
print(student[num_cols].isnull().sum())

for col in num_cols:
    student[col] = student[col].fillna(student[col].median())

print("\nAfter numerical columns")
print("*" * 30)
print(student[num_cols].isnull().sum())

Before numerical columns
******************************
AttendanceRate               1
StudyHoursPerWeek            1
PreviousGrade                1
ExtracurricularActivities    1
FinalGrade                   1
Study_Hours                  1
Attendance_                  1
dtype: int64

After numerical columns
******************************
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
FinalGrade                   0
Study_Hours                  0
Attendance_                  0
dtype: int64

In [16]:
cat_cols = student.select_dtypes(include='object').columns

print("Before numerical columns")
print("*" * 30)
print(student[cat_cols].isnull().sum())

for col in cat_cols:
    student[col] = student[col].fillna(student[col].mode()[0])

print("After numerical columns")
print("*" * 30)
print(student[cat_cols].isnull().sum())

Before numerical columns
******************************
Gender             1
ParentalSupport    1
dtype: int64
After numerical columns
******************************
Gender             0
ParentalSupport    0
dtype: int64

In [17]:
print("Number of duplicate rows:", student.duplicated().sum())

student = student.drop_duplicates()

print("Shape after removing duplicates:", student.shape)

Number of duplicate rows: 0
Shape after removing duplicates: (150, 10)

In [18]:
print("Categorical Columns:")
print(cat_cols)

le = LabelEncoder()

for col in cat_cols:
    student[col] = le.fit_transform(student[col])

student.head()

Categorical Columns:
Index(['Gender', 'ParentalSupport'], dtype='object')

,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study_Hours,Attendance_,Online_Classes_Taken
0,1,80.0,12.0,80.0,0.0,2,46.0,2.4,80.0,True
1,0,80.0,12.0,85.0,3.0,1,51.0,2.6,80.0,False
2,1,70.0,12.0,92.0,2.0,2,53.0,3.7,70.0,False
3,1,85.0,15.0,75.0,0.0,2,53.0,2.9,85.0,False
4,1,85.0,25.0,55.0,3.0,2,53.0,6.6,98.0,False

In [20]:
X = student.drop('FinalGrade', axis=1)
y = student['FinalGrade']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (120, 9)
X_test : (30, 9)
y_train: (120,)
y_test : (30,)

In [22]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [23]:
print("Training data shape:", X_train_scaled.shape)
print("Testing data shape :", X_test_scaled.shape)

Training data shape: (120, 9)
Testing data shape : (30, 9)

In [24]:
print("\nMissing values in X_train:")
print(X_train.isnull().sum().sum())

print("\nMissing values in X_test:")
print(X_test.isnull().sum().sum())

Missing values in X_train:
0

Missing values in X_test:
0

In [25]:
print("\nFirst 5 rows of scaled training data:")
print(X_train_scaled[:5])

First 5 rows of scaled training data:
[[-0.91986621 -0.62332896 -1.12843603 -0.07294369  0.47676115 -0.17791287
  -0.54788206 -0.65387273 -0.90453403]
 [ 1.08711461  0.79467057 -0.44176096 -0.07294369 -0.3900773  -1.36399867
  -0.22347821  0.77060038 -0.90453403]
 [-0.91986621  1.14917046 -0.853766    1.35787482  0.47676115 -0.17791287
  -0.54788206  1.12671866  1.1055416 ]
 [ 1.08711461 -1.2141621   0.93158918  0.51621688 -1.25691575 -1.36399867
   0.91193526 -1.24740319 -0.90453403]
 [-0.91986621  0.55833732  0.24491411 -0.07294369 -0.3900773  -1.36399867
   0.42532949  0.5331882   1.1055416 ]]

In [26]:
student.to_csv("cleaned_student_performance.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.